### ISSUE TITLE
تحديد اللغة في صفحة الدفع

### ISSUE THREAD

**Issue by drboudjelida** [Chargily/epay-gateway-php#6]
السلام عليكم،

هل يمكن  اضافة خيار تحديد اللغة في صفحة الدفع؟
مثلا في عند كل من CIB أو EDAHABIA تظهر صفحة الدفع بالفرنسية بشكل افتراضي.
لكن لو تلاحظ في الرابط يوجد ملف **payment_fr.html** بنسخة الفرنسية يمكن تعديله الى النسخة العربية **payment_ar.html**

![cib_fr](https://user-images.githubusercontent.com/76773604/203073739-05c76bbe-b5c2-4bf6-976a-400dece2e7b4.png)
![edahabia_fr](https://user-images.githubusercontent.com/76773604/203073819-8b8b64d6-cdca-4a8b-9897-d24a8abc2930.JPG)

بعد التعديل الى payment_ar.html تظهر النسخة العربية

![cib_ar](https://user-images.githubusercontent.com/76773604/203073710-0a59c053-6200-47de-a0d7-177d847d2796.png)
![edahabia_ar](https://user-images.githubusercontent.com/76773604/203073790-2f9d3669-4b8c-4131-8c28-c2463557542b.JPG)

هل يمكن اضافة متغير عند انشاء طلب جديد يتم تحديد فيه لغة الواجهة اذا عربية أو فرنسية
وهذا لتسهيل عملية الدفع على العملاء.

بارك الله فيكم.

**Comment by drboudjelida** [comment]
هل من تعليق؟ @Medboubazine

**Comment by Medboubazine** [comment]
@abdelhakpro 
أولا أعتذر عالرد المتأخر
الخاصية هذي حاليا غير متوفرة . لكن سيتم اضافاتها في التحديث القادم باذن الله
