### ISSUE TITLE
عدم ارسال تحديث الحالة PROCESSING الى webhook

### ISSUE THREAD

**Issue by drboudjelida** [Chargily/epay-gateway-php#7]
السلام عليكم،

عند ضغط المستخدم على زر Payer وانتقاله الى صفحة الدفع (إما CIB او EDAHABIA)

![payer btn](https://user-images.githubusercontent.com/76773604/204504314-479ee1d7-4af4-4b00-87c7-7a5173de5ca6.JPG)

لا يتم ارسال معلومات الى Webhook أن العملية أصبحت في حالة PROCESSING.

في حين انه لو تتحقق داخل لوحة التحكم https://epay.chargily.com/secure/admin/resources/invoice-managers
ستجد ان حالة العملية تغيرت من PENDING الى PROCESSING.

![admin trx status](https://user-images.githubusercontent.com/76773604/204504306-bf6f8387-d4ee-4079-a4a1-4bc8412b099f.JPG)

هل المشكلة من عندي ؟ ام أنها غير موجودة ضمن API ؟

بارك الله فيكم.

**Comment by Medboubazine** [comment]
وعليكم السلام ورحمة الله تعالى وبركاته

نعم لا يتم ارسال المعلومات عند تحديث حالة الدفع من PENDING الى PROCESSING
ترسل فقط عند تحديث حالة الدفع التي بعد PROCESSING


### الحالات التي تأتي بعد PROCESSING
**PROCESSING** =>**PAID**

**PROCESSING** => **CANCELED**

**PROCESSING** => **FAILED**

**Comment by drboudjelida** [comment]
بارك الله فيك على الرد والاهتمام، للغلق.
